#!/bin/bash
grep -E '<td>.+<\/td>' | \
sed -n '1~2!p' | \
tr '[:upper:]' '[:lower:]' | \
sed 's/<\/*[a-zA-Z]*>//g' | \
sed -e "s/\`/\'/g" | \
sed 's/, /\n/g' | \
sed 's/ /\n/g' | \
tr -d '[:blank:]' | \
sed '/-/d' | \
tr -cs "pk\'mnwlhaeiou" '[\n*]' | \
sort -u | \
sed '/^$/d'

